import 'dotenv/config'

export const env = {
    MONGODB_URI: process.env.MONGODB_URI,
    DATABASE_NAME: process.env.DATABASE_NAME,
    APP_HOST : process.env.APP_HOST,
    APP_PORT : process.env.APP_PORT,
    AUTHOR: process.env.AUTHOR,
    ACCESS_TOKEN_SIGNATURE: process.env.ACCESS_TOKEN_SIGNATURE,
    REFRESH_TOKEN_SIGNATURE: process.env.REFRESH_TOKEN_SIGNATURE,
    WEBSITE_DOMAIN_DEVELOPMENT:process.env.WEBSITE_DOMAIN_DEVELOPMENT,
    WEBSITE_DOMAIN_PRODUCTION:process.env.WEBSITE_DOMAIN_PRODUCTION,

    BREVO_API_KEY: process.env.BREVO_API_KEY,
    ADMIN_EMAIL_ADDRESS: process.env.ADMIN_EMAIL_ADDRESS,
    ADMIN_EMAIL_NAME: process.env.ADMIN_EMAIL_NAME,

    CLOUDINARY_CLOUD_NAME : process.env.CLOUDINARY_CLOUD_NAME,
    CLOUDINARY_API_KEY : process.env.CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET : process.env.CLOUDINARY_API_SECRET
}